version: 0.0.1.{build}
image: Visual Studio 2019
clone_depth: 1
branches:
  only:
    - master
init:
  - git config --global core.autocrlf input
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet build
after_build:
test: off

